services:
  portfolio:
    build: .
    ports:
      - "3008:3000"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - TELEGRAM_BOT_TOKEN=8658003214:AAFJykQiREH5G2AYPZkzjB7O38wglOXm618
      - TELEGRAM_CHAT_ID=7615070484
